### ISSUE TITLE
Bootstrap template don't work

### ISSUE THREAD

**Issue by Cuchulain** [iPublikuj/confirmation-dialog#8]
In Bootstrap template don't work submit form (and callback handler) after button press..

**Comment by akadlec** [comment]
Tested and its working. Provide more info

**Comment by Cuchulain** [comment]
I use jQuery v.1.11.2, jQuery UI v.1.9.2 and Bootstrap v.3.3.6.
When I press any button on modal form, dialog close, but don't send any request to server.

**Comment by akadlec** [comment]
JS impelemntation is not part of this extension. So it is up to you how you implement JS actions. If some classes etc. are missing in template, just create PR

**Comment by Barvoj** [comment]
I also have this problem. I bealeve that it is related to [this line](https://github.com/twbs/bootstrap/blob/master/js/modal.js#L110) of bootstrap. It prevents submit behavior of button.

**Comment by akadlec** [comment]
But this is only for close button

**Comment by Barvoj** [comment]
I thing it is also for **yes** and **no** buttons.. There is `data-dismiss="modal"` on [bootstrap.latte](data-dismiss="modal"). Removing this attribute helped me (in my non ajax use case).
