### ISSUE TITLE
Dialog box not showing

### ISSUE THREAD

**Issue by Tatranskymedved** [iPublikuj/confirmation-dialog#9]
Hello, I'm facing an issue where the dialog box is not shown at all, however the source code (result) is injected to the HTML.

I believe this dialog should be working and issue is just that I have not called proper function in JS? It would be great if the process of the call (show) would be described at documentation. 

Another great (and to be done) thing in documentation would be a working example of such dialog, e.g. compiled code that is send to client (shortened version) and the image of dialog screen with all basic templates. This would help troubleshoot the issue without going further to extension.

I'd rather add these myself, but at the moment I need to resolve the issue. Would You mind to describe how the window should be shown?

**Comment by Tatranskymedved** [comment]
I looked further into this, actually the methods for redrawing control are called and the snippets invalidated, so basically everything should be shown.

There is whole code that is rendered:

```
<div id="snippet-confirmDeleteAction-dialog-area">
  <div class="overlay --overlay"></div>
  <form data-ajax-off="['history','scrollTo']" class="confirmation-dialog modal" action="/myWeb/www/admin/udalosti" method="post" id="frm-confirmDeleteAction-confirmer-confirmerDeleteAction-form">
    <div class="modal-header">
      <h3 class="modal-title">Smazání události</h3>
    </div>
    <div class="modal-body">
      <div class="alert-icon alert-icon-trash">&nbsp;</div>
            Opravdu si přejete smazat událost: Tohle je test 2
    </div>
    <div class="modal-footer">
      <button class="btn btn-danger" data-ajax-off="['history','scrollTo']" type="submit" name="yes" value="Yes">Yes</button>
      <button class="btn btn-default" data-ajax-off="['history','scrollTo']" type="submit" name="no" value="No">No</button>
    </div>
    <input type="hidden" name="_token_" value="yxhckfuyy5IW865jGq1sgZtes+DJEsnDbiPBg=">
    <input type="hidden" name="secureToken" value="b03pvoyadg0880g4ok8004ckw"><input type="hidden" name="_do" value="confirmDeleteAction-confirmer-confirmerDeleteAction-form-submit"><!--[if IE]>
    <input type=IEbug disabled style="display:none"><![endif]-->
  </form>
</div>
```

**Comment by akadlec** [comment]
This extension is JS less version. You have to impement your solution. Showing dialog is depend on what are you using. Modal from BS, plain jQuery modal, modal from UiKit etc. You could choose one from predefined templates for bootstrap, uikit or plain template, but you have to write your JS code if is needed
